[tools]
typos = "latest"
dprint = "latest"
actionlint = "latest"
zizmor = "latest"

[tasks.default]
hide = true
run = ["mise run curate"]

[tasks.setup]
hide = true
confirm = 'Are you sure?'
description = "Setup the project"
depends = ["hooks"]

[tasks.hooks]
hide = true
description = "Setup Git hooks"
run = "mise run hooks"

[tasks.clean]
hide = true
description = "Clean target output"
run = "rm -rf curated"

[tasks.qc]
description = "Fix before check"
depends = ["fix", "qq"]

[tasks.qqq]
description = "Exhaustive quality check"
depends = ["qa", "lint-nu", "meta"]

[tasks.qq]
description = "Quality check"
depends = ["qa"]

[tasks.qa]
description = "Quick quality check"
depends = ["fmt-check", "lint"]

[tasks.fix]
description = "Enforce rules"
depends = ["fmt", "lint"]

[tasks.curate]
description = "Curate"
depends = ["fmt", "lint"]
run = "SOURCE=~/labs/forks/ubuntu-wallpapers-upstream nu src/curate.nu"

[tasks.fmt]
hide = true
description = "Format"
run = ["dprint fmt"]

[tasks.fmt-check]
hide = true
description = "Check formatting"
run = ["dprint check"]

[tasks.lint]
hide = true
description = "Lint"
depends = ["fmt-check"]
run = "typos"

[tasks.lint-nu]
hide = true
description = "Lint Nushell code"
run = "nu-lint src/"

[tasks.release]
hide = true
description = "Create a new release"
run = "./release {{arg(name='version')}}"

[tasks.up]
hide = true
description = "Upgrade dependencies"
run = "dprint config update"

[tasks.meta]
hide = true
description = "Dependency analysis"
run = ["pnpx actions-up", "actionlint", "zizmor .github/workflows/*"]

[tasks.package] # CI
hide = true
description = "Create release tarball"
depends = ["curate"]
run = "scripts/package.sh"
env = { REPO_NAME = "ubuntu-wallpapers", RELEASE_VERSION = "{{arg(name='version')}}" }
