name: CI

on: [push, pull_request]

jobs:
  code_quality:
    name: Code Quality
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: 'clippy, rustfmt'

      - uses: taiki-e/install-action@v2
        with:
          tool: 'just,dprint,typos'

      - name: Ensure `fmt` has been run
        run: just fmt-check

      - name: Run clippy
        run: just lint
